# Generated by Django 2.2.13 on 2023-07-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('recipient_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('completion_date', models.DateField()),
            ],
        ),
    ]
